### ISSUE TITLE
`generic_issubclass()`

### ISSUE THREAD

**Issue by bswck** [bswck/runtime_generics#5]
### Use case

Implement `generic_issubclass()` with covariance and contravariance in mind.

**Comment by bswck** [comment]
@benedikt-bartscher in case you were waiting for this feature, you can use the new `runtime_generics.type_check()` [released in v3.1.0](https://github.com/bswck/runtime_generics/releases/tag/v3.1.0).

**Comment by benedikt-bartscher** [comment]
@bswck yes, I still need it. Thank you very much for mentioning! :heart:
